insert into public.products (name, price, type)
values
  ('Espresso', 120, 'Hot Coffees'),
  ('Cappuccino', 180, 'Hot Coffees'),
  ('Mocha Frappe', 240, 'Frappes'),
  ('Caramel Frappe', 250, 'Frappes'),
  ('Iced Americano', 170, 'Iced Sections'),
  ('Iced Latte', 210, 'Iced Sections'),
  ('Virgin Mojito', 210, 'Mocktails'),
  ('Berry Sparkler', 220, 'Mocktails'),
  ('Chocolate Shake', 260, 'Shakes & Smoothies'),
  ('Mango Smoothie', 250, 'Shakes & Smoothies'),
  ('Blue Lagoon Slush', 190, 'Slushes'),
  ('Watermelon Slush', 190, 'Slushes'),
  ('Loaded Fries', 220, 'Small Bites'),
  ('Chicken Nuggets', 240, 'Small Bites'),
  ('Classic Veg Burger', 260, 'Burgers'),
  ('Smoked Chicken Burger', 290, 'Burgers'),
  ('Grilled Cheese Sandwich', 210, 'Sandwiches'),
  ('Chicken Club Sandwich', 260, 'Sandwiches'),
  ('Margherita Pizza', 340, 'Pizza'),
  ('Peri Peri Chicken Pizza', 390, 'Pizza'),
  ('Arrabbiata Pasta', 300, 'Pasta'),
  ('Alfredo Chicken Pasta', 340, 'Pasta'),
  ('Brownie Sundae', 220, 'Desserts'),
  ('Tiramisu Jar', 240, 'Desserts');
